language: node_js
sudo: false
services:
- mongodb
node_js:
- '0.10'
env:
- NODE_ENV=travis
deploy:
- provider: s3
  access_key_id: AKIAIEAMLPHO36E7S73Q
  secret_access_key: &24314640
    secure: odOjsW3uSH1TePNv4jV65Qo2csId1vT2kBogHZvkXjsT0jmSZSLPx2m0hXd+KzjDgnjnO++GqrL0cOPZNtDYh6PDzJpazFrVwHR9pohOrlC2WuB/8Fgw4skF6q3H1yC2JOa/WQ6Eq+GHyXUIXaFI7UcNi5eQzgYreCqCH4oCDBN1RGsxZ03a/+ZGblavmkyJ/RiETwBhQnGOUbGsZwUBrviQxxVTWlST8UZYQl1SSRcn+QdmnQYDTZdAUt7L6hjZyVQUK4tZ8a0UTOgtvHJrsfP85WRnebhaNDXCBQmhmTTd/tsm8PgNgkdEH+Su1hCvp3Kjczu5r6CrPhcpgU3WBqDnH/CdwKr/4rITtDNty1sF4FuFVwOC7m5REIHq95lvbbi0bEl9BK/GR3Kt/ZZl0Ua+5Ni0fA+M7iPBl/P0nl3zh8l2fxH18ro+v6L4D0VjBJDLkzY/VttEyoqCmt/KOrjQ60wORQXV1Apr0rSfXCv83ySBJVql6cOyH9PwAui525/2oC10NFXi2ZVtx2OQx2kHOFPmeiV4EtATaZ99pao4oh03hOlvCTQoRZgpYlYviAN1F+Hd37zkeCFpMQ0vO1rtYBkk2wuBMZSqj0bkWbsy8LTmzuTKzNQfUkL0tlrRcMShMAeDWm340/NWduhW7OSGb+fRPmgfwwPgYyyejso=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &24310220
    repo: nbuechler/log-grower
    branch: develop
  bucket: log-grower-bucket
- provider: codedeploy
  access_key_id: AKIAIEAMLPHO36E7S73Q
  secret_access_key: *24314640
  bucket: log-grower-bucket
  key: latest-lg.zip
  bundle_type: zip
  application: log-grower
  deployment_group: logro-development-group
  on: *24310220
before_deploy:
  - zip -r latest-lg app/* config/* public/* scripts/* test/* .bowerrc .csslintrc .gitignore .jshintrc .slugignore .travis.yml appspec.yml bower.json gruntfile.js LICENSE package.json Procfile README.md server.js
  - mkdir -p dpl_cd_upload
  - mv latest-lg.zip dpl_cd_upload/latest-lg.zip
